/**
 * Auto-generate public/sitemap.xml from live data at build time.
 *
 * Runs automatically before every `npm run build` (see the "prebuild" script in
 * package.json). It writes the static routes plus one <url> per live property
 * fetched from the backend API, with today's date as <lastmod>.
 *
 * FAIL-SAFE: if the API is unreachable (e.g. building offline), it logs a
 * warning and LEAVES THE EXISTING sitemap.xml untouched — a build never ships an
 * empty/broken sitemap. Exit code is always 0 so the build proceeds regardless.
 *
 * Override the API host with REACT_APP_API_URL (same var the app uses).
 */
const fs = require('fs');
const path = require('path');

const SITE_URL = 'https://ijestateandbuilders.com';
const API_URL = process.env.REACT_APP_API_URL || 'https://www.ijestateandbuilders.tech';
const OUT_FILE = path.join(__dirname, '..', 'public', 'sitemap.xml');
const TODAY = new Date().toISOString().slice(0, 10); // YYYY-MM-DD

// Static routes — keep in sync with your keyword map / react-snap routes.
// [path, changefreq, priority]
const STATIC_ROUTES = [
  ['/', 'daily', '1.0'],
  ['/listings', 'daily', '0.9'],
  ['/about', 'monthly', '0.7'],
  ['/contact', 'monthly', '0.7'],
  ['/commercial/business-bay', 'weekly', '0.8'],
  ['/commercial/generic', 'monthly', '0.6'],
  ['/map', 'weekly', '0.6'],
  ['/virtual-3d', 'monthly', '0.6'],
  ['/forums', 'daily', '0.6'],
];

function urlBlock(loc, changefreq, priority) {
  return (
    `  <url>\n` +
    `    <loc>${SITE_URL}${loc}</loc>\n` +
    `    <lastmod>${TODAY}</lastmod>\n` +
    `    <changefreq>${changefreq}</changefreq>\n` +
    `    <priority>${priority}</priority>\n` +
    `  </url>`
  );
}

// Fetch every property id, following DRF pagination (?page=N -> {results, next}).
async function fetchAllPropertyIds() {
  const ids = [];
  let url = `${API_URL}/api/properties/`;
  let guard = 0; // never loop forever on a misbehaving API
  while (url && guard < 100) {
    guard += 1;
    const res = await fetch(url, { headers: { Accept: 'application/json' } });
    if (!res.ok) throw new Error(`API responded ${res.status} for ${url}`);
    const data = await res.json();
    const results = Array.isArray(data) ? data : data.results || [];
    for (const p of results) if (p && p.id != null) ids.push(p.id);
    url = Array.isArray(data) ? null : data.next || null;
  }
  return ids;
}

async function main() {
  let propertyIds;
  try {
    propertyIds = await fetchAllPropertyIds();
  } catch (err) {
    console.warn(
      `⚠️  generate-sitemap: could not reach the API (${err.message}).\n` +
      `    Keeping the existing public/sitemap.xml untouched.`
    );
    return; // fail-safe: leave the committed sitemap as-is
  }

  const blocks = [
    ...STATIC_ROUTES.map(([loc, cf, pr]) => urlBlock(loc, cf, pr)),
    ...propertyIds.map((id) => urlBlock(`/property/${id}`, 'weekly', '0.8')),
  ];

  const xml =
    `<?xml version="1.0" encoding="UTF-8"?>\n` +
    `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"\n` +
    `        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">\n\n` +
    `  <!-- Auto-generated by scripts/generate-sitemap.js on ${TODAY}. Do not edit by hand. -->\n\n` +
    blocks.join('\n') +
    `\n\n</urlset>\n`;

  fs.writeFileSync(OUT_FILE, xml, 'utf8');
  console.log(
    `✅ generate-sitemap: wrote ${STATIC_ROUTES.length} static + ` +
    `${propertyIds.length} property URLs to public/sitemap.xml`
  );
}

main();
